/*
 * generated by Xtext 2.22.0
 */
package xCalendar.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import xCalendar.ide.contentassist.antlr.internal.InternalMyDslParser;
import xCalendar.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getComponentAccess().getAlternatives(), "rule__Component__Alternatives");
			builder.put(grammarAccess.getAlarmTypeAccess().getAlternatives(), "rule__AlarmType__Alternatives");
			builder.put(grammarAccess.getMonthAccess().getAlternatives(), "rule__Month__Alternatives");
			builder.put(grammarAccess.getMonthNameTAccess().getValueAlternatives_0(), "rule__MonthNameT__ValueAlternatives_0");
			builder.put(grammarAccess.getDateTAccess().getAlternatives_4_0(), "rule__DateT__Alternatives_4_0");
			builder.put(grammarAccess.getDateTAccess().getAlternatives_4_2(), "rule__DateT__Alternatives_4_2");
			builder.put(grammarAccess.getDateTAccess().getAlternatives_4_3_1(), "rule__DateT__Alternatives_4_3_1");
			builder.put(grammarAccess.getDateTAccess().getAlternatives_4_4_2(), "rule__DateT__Alternatives_4_4_2");
			builder.put(grammarAccess.getStatusAccess().getAlternatives(), "rule__Status__Alternatives");
			builder.put(grammarAccess.getEventStatusAccess().getAlternatives(), "rule__EventStatus__Alternatives");
			builder.put(grammarAccess.getICalFormatAccess().getGroup(), "rule__ICalFormat__Group__0");
			builder.put(grammarAccess.getCalendarAccess().getGroup(), "rule__Calendar__Group__0");
			builder.put(grammarAccess.getCalendarAccess().getGroup_1(), "rule__Calendar__Group_1__0");
			builder.put(grammarAccess.getDateTAccess().getGroup(), "rule__DateT__Group__0");
			builder.put(grammarAccess.getDateTAccess().getGroup_4(), "rule__DateT__Group_4__0");
			builder.put(grammarAccess.getDateTAccess().getGroup_4_3(), "rule__DateT__Group_4_3__0");
			builder.put(grammarAccess.getDateTAccess().getGroup_4_4(), "rule__DateT__Group_4_4__0");
			builder.put(grammarAccess.getEventCAccess().getGroup(), "rule__EventC__Group__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_3(), "rule__EventC__Group_3__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_4(), "rule__EventC__Group_4__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_5(), "rule__EventC__Group_5__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_6(), "rule__EventC__Group_6__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_7(), "rule__EventC__Group_7__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_7_2(), "rule__EventC__Group_7_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_8(), "rule__EventC__Group_8__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_8_2(), "rule__EventC__Group_8_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_9(), "rule__EventC__Group_9__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_9_2(), "rule__EventC__Group_9_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_10(), "rule__EventC__Group_10__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_10_2(), "rule__EventC__Group_10_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_11(), "rule__EventC__Group_11__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_11_2(), "rule__EventC__Group_11_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_12(), "rule__EventC__Group_12__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_12_2(), "rule__EventC__Group_12_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_13(), "rule__EventC__Group_13__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_13_2(), "rule__EventC__Group_13_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_14(), "rule__EventC__Group_14__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_14_2(), "rule__EventC__Group_14_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_15(), "rule__EventC__Group_15__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_16(), "rule__EventC__Group_16__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_17(), "rule__EventC__Group_17__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_18(), "rule__EventC__Group_18__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_19(), "rule__EventC__Group_19__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_19_2(), "rule__EventC__Group_19_2__0");
			builder.put(grammarAccess.getAlarmCAccess().getGroup(), "rule__AlarmC__Group__0");
			builder.put(grammarAccess.getAlarmCAccess().getGroup_6(), "rule__AlarmC__Group_6__0");
			builder.put(grammarAccess.getAlarmCAccess().getGroup_7(), "rule__AlarmC__Group_7__0");
			builder.put(grammarAccess.getAlarmCAccess().getGroup_10(), "rule__AlarmC__Group_10__0");
			builder.put(grammarAccess.getTzpropAccess().getGroup(), "rule__Tzprop__Group__0");
			builder.put(grammarAccess.getTzpropAccess().getGroup_8(), "rule__Tzprop__Group_8__0");
			builder.put(grammarAccess.getTzpropAccess().getGroup_9(), "rule__Tzprop__Group_9__0");
			builder.put(grammarAccess.getTzpropAccess().getGroup_9_3(), "rule__Tzprop__Group_9_3__0");
			builder.put(grammarAccess.getTzpropOptionalAccess().getGroup(), "rule__TzpropOptional__Group__0");
			builder.put(grammarAccess.getTzpropOptionalAccess().getGroup_3(), "rule__TzpropOptional__Group_3__0");
			builder.put(grammarAccess.getTzpropOptionalAccess().getGroup_4(), "rule__TzpropOptional__Group_4__0");
			builder.put(grammarAccess.getTzpropOptionalAccess().getGroup_5(), "rule__TzpropOptional__Group_5__0");
			builder.put(grammarAccess.getTzpropOptionalAccess().getGroup_6(), "rule__TzpropOptional__Group_6__0");
			builder.put(grammarAccess.getTzpropOptionalAccess().getGroup_7(), "rule__TzpropOptional__Group_7__0");
			builder.put(grammarAccess.getComponentAlarmTimeAccess().getGroup(), "rule__ComponentAlarmTime__Group__0");
			builder.put(grammarAccess.getComponentAlarmTimeAccess().getGroup_3(), "rule__ComponentAlarmTime__Group_3__0");
			builder.put(grammarAccess.getComponentAlarmTimeAccess().getGroup_4(), "rule__ComponentAlarmTime__Group_4__0");
			builder.put(grammarAccess.getComponentAlarmAudioPropertyAccess().getGroup(), "rule__ComponentAlarmAudioProperty__Group__0");
			builder.put(grammarAccess.getComponentAlarmAudioPropertyAccess().getGroup_3(), "rule__ComponentAlarmAudioProperty__Group_3__0");
			builder.put(grammarAccess.getComponentAlarmDispPropertyAccess().getGroup(), "rule__ComponentAlarmDispProperty__Group__0");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getGroup(), "rule__ComponentAlarmEmailProperty__Group__0");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getGroup_5(), "rule__ComponentAlarmEmailProperty__Group_5__0");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getGroup_9(), "rule__ComponentAlarmEmailProperty__Group_9__0");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getGroup_9_3(), "rule__ComponentAlarmEmailProperty__Group_9_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup(), "rule__ToDoC__Group__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_6(), "rule__ToDoC__Group_6__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_7(), "rule__ToDoC__Group_7__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_8(), "rule__ToDoC__Group_8__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_9(), "rule__ToDoC__Group_9__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_10(), "rule__ToDoC__Group_10__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_11(), "rule__ToDoC__Group_11__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_12(), "rule__ToDoC__Group_12__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_13(), "rule__ToDoC__Group_13__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_14(), "rule__ToDoC__Group_14__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_15(), "rule__ToDoC__Group_15__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_16(), "rule__ToDoC__Group_16__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_16_3(), "rule__ToDoC__Group_16_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_17(), "rule__ToDoC__Group_17__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_17_3(), "rule__ToDoC__Group_17_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_18(), "rule__ToDoC__Group_18__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_18_3(), "rule__ToDoC__Group_18_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_19(), "rule__ToDoC__Group_19__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_19_3(), "rule__ToDoC__Group_19_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_20(), "rule__ToDoC__Group_20__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_20_3(), "rule__ToDoC__Group_20_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_21(), "rule__ToDoC__Group_21__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_21_3(), "rule__ToDoC__Group_21_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_22(), "rule__ToDoC__Group_22__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_22_3(), "rule__ToDoC__Group_22_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_23(), "rule__ToDoC__Group_23__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_23_3(), "rule__ToDoC__Group_23_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_24(), "rule__ToDoC__Group_24__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_24_3(), "rule__ToDoC__Group_24_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_25(), "rule__ToDoC__Group_25__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_25_3(), "rule__ToDoC__Group_25_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_26(), "rule__ToDoC__Group_26__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_26_3(), "rule__ToDoC__Group_26_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_27(), "rule__ToDoC__Group_27__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_27_3(), "rule__ToDoC__Group_27_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_28(), "rule__ToDoC__Group_28__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_28_3(), "rule__ToDoC__Group_28_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_29(), "rule__ToDoC__Group_29__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_30(), "rule__ToDoC__Group_30__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_31(), "rule__ToDoC__Group_31__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_32(), "rule__ToDoC__Group_32__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_33(), "rule__ToDoC__Group_33__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_34(), "rule__ToDoC__Group_34__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_35(), "rule__ToDoC__Group_35__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_35_3(), "rule__ToDoC__Group_35_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup(), "rule__JournalC__Group__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_6(), "rule__JournalC__Group_6__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_7(), "rule__JournalC__Group_7__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_8(), "rule__JournalC__Group_8__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_9(), "rule__JournalC__Group_9__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_10(), "rule__JournalC__Group_10__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_11(), "rule__JournalC__Group_11__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_12(), "rule__JournalC__Group_12__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_13(), "rule__JournalC__Group_13__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_14(), "rule__JournalC__Group_14__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_15(), "rule__JournalC__Group_15__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_16(), "rule__JournalC__Group_16__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_16_3(), "rule__JournalC__Group_16_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_17(), "rule__JournalC__Group_17__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_17_3(), "rule__JournalC__Group_17_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_18(), "rule__JournalC__Group_18__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_18_3(), "rule__JournalC__Group_18_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_19(), "rule__JournalC__Group_19__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_19_3(), "rule__JournalC__Group_19_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_20(), "rule__JournalC__Group_20__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_20_3(), "rule__JournalC__Group_20_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_21(), "rule__JournalC__Group_21__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_21_3(), "rule__JournalC__Group_21_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_22(), "rule__JournalC__Group_22__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_22_3(), "rule__JournalC__Group_22_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_23(), "rule__JournalC__Group_23__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_23_3(), "rule__JournalC__Group_23_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_24(), "rule__JournalC__Group_24__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_24_3(), "rule__JournalC__Group_24_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_25(), "rule__JournalC__Group_25__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_25_3(), "rule__JournalC__Group_25_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_26(), "rule__JournalC__Group_26__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_26_3(), "rule__JournalC__Group_26_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_27(), "rule__JournalC__Group_27__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_27_3(), "rule__JournalC__Group_27_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_28(), "rule__JournalC__Group_28__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_28_3(), "rule__JournalC__Group_28_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_29(), "rule__JournalC__Group_29__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup(), "rule__VacationC__Group__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_6(), "rule__VacationC__Group_6__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_7(), "rule__VacationC__Group_7__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_8(), "rule__VacationC__Group_8__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_9(), "rule__VacationC__Group_9__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_10(), "rule__VacationC__Group_10__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_11(), "rule__VacationC__Group_11__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_11_3(), "rule__VacationC__Group_11_3__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_12(), "rule__VacationC__Group_12__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_12_3(), "rule__VacationC__Group_12_3__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_13(), "rule__VacationC__Group_13__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_13_3(), "rule__VacationC__Group_13_3__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_14(), "rule__VacationC__Group_14__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_14_3(), "rule__VacationC__Group_14_3__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_15(), "rule__VacationC__Group_15__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_15_3(), "rule__VacationC__Group_15_3__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_16(), "rule__VacationC__Group_16__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_16_3(), "rule__VacationC__Group_16_3__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup(), "rule__TimeZoneC__Group__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_4(), "rule__TimeZoneC__Group_4__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_5(), "rule__TimeZoneC__Group_5__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_6(), "rule__TimeZoneC__Group_6__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_6_3(), "rule__TimeZoneC__Group_6_3__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_7(), "rule__TimeZoneC__Group_7__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_7_3(), "rule__TimeZoneC__Group_7_3__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_8(), "rule__TimeZoneC__Group_8__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_8_3(), "rule__TimeZoneC__Group_8_3__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_9(), "rule__TimeZoneC__Group_9__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_9_3(), "rule__TimeZoneC__Group_9_3__0");
			builder.put(grammarAccess.getICalFormatAccess().getFileNameAssignment_1(), "rule__ICalFormat__FileNameAssignment_1");
			builder.put(grammarAccess.getICalFormatAccess().getCalendarAssignment_3(), "rule__ICalFormat__CalendarAssignment_3");
			builder.put(grammarAccess.getCalendarAccess().getComponentAssignment_0(), "rule__Calendar__ComponentAssignment_0");
			builder.put(grammarAccess.getCalendarAccess().getComponentAssignment_1_1(), "rule__Calendar__ComponentAssignment_1_1");
			builder.put(grammarAccess.getMonthNameTAccess().getValueAssignment(), "rule__MonthNameT__ValueAssignment");
			builder.put(grammarAccess.getMonthTAccess().getValueAssignment(), "rule__MonthT__ValueAssignment");
			builder.put(grammarAccess.getDateTAccess().getDay_nameAssignment_0(), "rule__DateT__Day_nameAssignment_0");
			builder.put(grammarAccess.getDateTAccess().getDayAssignment_1(), "rule__DateT__DayAssignment_1");
			builder.put(grammarAccess.getDateTAccess().getMonthAssignment_2(), "rule__DateT__MonthAssignment_2");
			builder.put(grammarAccess.getDateTAccess().getYearAssignment_3(), "rule__DateT__YearAssignment_3");
			builder.put(grammarAccess.getDateTAccess().getHoursAssignment_4_1(), "rule__DateT__HoursAssignment_4_1");
			builder.put(grammarAccess.getDateTAccess().getMinutesAssignment_4_3_0(), "rule__DateT__MinutesAssignment_4_3_0");
			builder.put(grammarAccess.getDateTAccess().getSecondsAssignment_4_4_1(), "rule__DateT__SecondsAssignment_4_4_1");
			builder.put(grammarAccess.getEventCAccess().getDtstartAssignment_2(), "rule__EventC__DtstartAssignment_2");
			builder.put(grammarAccess.getEventCAccess().getUidAssignment_3_1(), "rule__EventC__UidAssignment_3_1");
			builder.put(grammarAccess.getEventCAccess().getOrganizerAssignment_4_1(), "rule__EventC__OrganizerAssignment_4_1");
			builder.put(grammarAccess.getEventCAccess().getSummaryAssignment_5_1(), "rule__EventC__SummaryAssignment_5_1");
			builder.put(grammarAccess.getEventCAccess().getUrlAssignment_6_1(), "rule__EventC__UrlAssignment_6_1");
			builder.put(grammarAccess.getEventCAccess().getAttachAssignment_7_1(), "rule__EventC__AttachAssignment_7_1");
			builder.put(grammarAccess.getEventCAccess().getAttachAssignment_7_2_1(), "rule__EventC__AttachAssignment_7_2_1");
			builder.put(grammarAccess.getEventCAccess().getAttendeeAssignment_8_1(), "rule__EventC__AttendeeAssignment_8_1");
			builder.put(grammarAccess.getEventCAccess().getAttendeeAssignment_8_2_1(), "rule__EventC__AttendeeAssignment_8_2_1");
			builder.put(grammarAccess.getEventCAccess().getCategoriesAssignment_9_1(), "rule__EventC__CategoriesAssignment_9_1");
			builder.put(grammarAccess.getEventCAccess().getCategoriesAssignment_9_2_1(), "rule__EventC__CategoriesAssignment_9_2_1");
			builder.put(grammarAccess.getEventCAccess().getCommentAssignment_10_1(), "rule__EventC__CommentAssignment_10_1");
			builder.put(grammarAccess.getEventCAccess().getCommentAssignment_10_2_1(), "rule__EventC__CommentAssignment_10_2_1");
			builder.put(grammarAccess.getEventCAccess().getContactAssignment_11_1(), "rule__EventC__ContactAssignment_11_1");
			builder.put(grammarAccess.getEventCAccess().getContactAssignment_11_2_1(), "rule__EventC__ContactAssignment_11_2_1");
			builder.put(grammarAccess.getEventCAccess().getRstatusAssignment_12_1(), "rule__EventC__RstatusAssignment_12_1");
			builder.put(grammarAccess.getEventCAccess().getRstatusAssignment_12_2_1(), "rule__EventC__RstatusAssignment_12_2_1");
			builder.put(grammarAccess.getEventCAccess().getRelatedAssignment_13_1(), "rule__EventC__RelatedAssignment_13_1");
			builder.put(grammarAccess.getEventCAccess().getRelatedAssignment_13_2_1(), "rule__EventC__RelatedAssignment_13_2_1");
			builder.put(grammarAccess.getEventCAccess().getResourcesAssignment_14_1(), "rule__EventC__ResourcesAssignment_14_1");
			builder.put(grammarAccess.getEventCAccess().getResourcesAssignment_14_2_1(), "rule__EventC__ResourcesAssignment_14_2_1");
			builder.put(grammarAccess.getEventCAccess().getDescriptionAssignment_15_1(), "rule__EventC__DescriptionAssignment_15_1");
			builder.put(grammarAccess.getEventCAccess().getPriorityAssignment_16_1(), "rule__EventC__PriorityAssignment_16_1");
			builder.put(grammarAccess.getEventCAccess().getLocationAssignment_17_1(), "rule__EventC__LocationAssignment_17_1");
			builder.put(grammarAccess.getEventCAccess().getDtendAssignment_18_1(), "rule__EventC__DtendAssignment_18_1");
			builder.put(grammarAccess.getEventCAccess().getAlarmcAssignment_19_1(), "rule__EventC__AlarmcAssignment_19_1");
			builder.put(grammarAccess.getEventCAccess().getAlarmcAssignment_19_2_1(), "rule__EventC__AlarmcAssignment_19_2_1");
			builder.put(grammarAccess.getAlarmCAccess().getActionAssignment_3(), "rule__AlarmC__ActionAssignment_3");
			builder.put(grammarAccess.getAlarmCAccess().getTriggerAssignment_5(), "rule__AlarmC__TriggerAssignment_5");
			builder.put(grammarAccess.getAlarmCAccess().getAttachAssignment_6_1(), "rule__AlarmC__AttachAssignment_6_1");
			builder.put(grammarAccess.getAlarmCAccess().getDescriptionAssignment_7_1(), "rule__AlarmC__DescriptionAssignment_7_1");
			builder.put(grammarAccess.getAlarmCAccess().getTypeAssignment_9(), "rule__AlarmC__TypeAssignment_9");
			builder.put(grammarAccess.getAlarmCAccess().getTimeAssignment_10_1(), "rule__AlarmC__TimeAssignment_10_1");
			builder.put(grammarAccess.getTzpropAccess().getDtstartAssignment_3(), "rule__Tzprop__DtstartAssignment_3");
			builder.put(grammarAccess.getTzpropAccess().getTzoffsetoAssignment_5(), "rule__Tzprop__TzoffsetoAssignment_5");
			builder.put(grammarAccess.getTzpropAccess().getTzoffsetfromAssignment_7(), "rule__Tzprop__TzoffsetfromAssignment_7");
			builder.put(grammarAccess.getTzpropAccess().getRruleAssignment_8_1(), "rule__Tzprop__RruleAssignment_8_1");
			builder.put(grammarAccess.getTzpropAccess().getOptAssignment_9_2(), "rule__Tzprop__OptAssignment_9_2");
			builder.put(grammarAccess.getTzpropAccess().getOptAssignment_9_3_1(), "rule__Tzprop__OptAssignment_9_3_1");
			builder.put(grammarAccess.getTzpropOptionalAccess().getCommentAssignment_3_1(), "rule__TzpropOptional__CommentAssignment_3_1");
			builder.put(grammarAccess.getTzpropOptionalAccess().getRdateAssignment_4_1(), "rule__TzpropOptional__RdateAssignment_4_1");
			builder.put(grammarAccess.getTzpropOptionalAccess().getTznameAssignment_5_1(), "rule__TzpropOptional__TznameAssignment_5_1");
			builder.put(grammarAccess.getTzpropOptionalAccess().getX_propAssignment_6_1(), "rule__TzpropOptional__X_propAssignment_6_1");
			builder.put(grammarAccess.getTzpropOptionalAccess().getIana_propAssignment_7_1(), "rule__TzpropOptional__Iana_propAssignment_7_1");
			builder.put(grammarAccess.getComponentAlarmTimeAccess().getDurationAssignment_3_1(), "rule__ComponentAlarmTime__DurationAssignment_3_1");
			builder.put(grammarAccess.getComponentAlarmTimeAccess().getRepeatAssignment_4_1(), "rule__ComponentAlarmTime__RepeatAssignment_4_1");
			builder.put(grammarAccess.getComponentAlarmAudioPropertyAccess().getAttachAssignment_3_1(), "rule__ComponentAlarmAudioProperty__AttachAssignment_3_1");
			builder.put(grammarAccess.getComponentAlarmDispPropertyAccess().getDescriptionAssignment_3(), "rule__ComponentAlarmDispProperty__DescriptionAssignment_3");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getAttendeeAssignment_4(), "rule__ComponentAlarmEmailProperty__AttendeeAssignment_4");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getAttendeeAssignment_5_1(), "rule__ComponentAlarmEmailProperty__AttendeeAssignment_5_1");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getDescriptionAssignment_8(), "rule__ComponentAlarmEmailProperty__DescriptionAssignment_8");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getAttachAssignment_9_2(), "rule__ComponentAlarmEmailProperty__AttachAssignment_9_2");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getAttachAssignment_9_3_1(), "rule__ComponentAlarmEmailProperty__AttachAssignment_9_3_1");
			builder.put(grammarAccess.getToDoCAccess().getDtstampAssignment_3(), "rule__ToDoC__DtstampAssignment_3");
			builder.put(grammarAccess.getToDoCAccess().getUidAssignment_5(), "rule__ToDoC__UidAssignment_5");
			builder.put(grammarAccess.getToDoCAccess().getDtstartAssignment_6_1(), "rule__ToDoC__DtstartAssignment_6_1");
			builder.put(grammarAccess.getToDoCAccess().getClassAssignment_7_1(), "rule__ToDoC__ClassAssignment_7_1");
			builder.put(grammarAccess.getToDoCAccess().getCreatedAssignment_8_1(), "rule__ToDoC__CreatedAssignment_8_1");
			builder.put(grammarAccess.getToDoCAccess().getLast_modAssignment_9_1(), "rule__ToDoC__Last_modAssignment_9_1");
			builder.put(grammarAccess.getToDoCAccess().getOrganizerAssignment_10_1(), "rule__ToDoC__OrganizerAssignment_10_1");
			builder.put(grammarAccess.getToDoCAccess().getSeqAssignment_11_1(), "rule__ToDoC__SeqAssignment_11_1");
			builder.put(grammarAccess.getToDoCAccess().getStatusAssignment_12_1(), "rule__ToDoC__StatusAssignment_12_1");
			builder.put(grammarAccess.getToDoCAccess().getSummaryAssignment_13_1(), "rule__ToDoC__SummaryAssignment_13_1");
			builder.put(grammarAccess.getToDoCAccess().getUrlAssignment_14_1(), "rule__ToDoC__UrlAssignment_14_1");
			builder.put(grammarAccess.getToDoCAccess().getRecuridAssignment_15_1(), "rule__ToDoC__RecuridAssignment_15_1");
			builder.put(grammarAccess.getToDoCAccess().getRruleAssignment_16_2(), "rule__ToDoC__RruleAssignment_16_2");
			builder.put(grammarAccess.getToDoCAccess().getRruleAssignment_16_3_1(), "rule__ToDoC__RruleAssignment_16_3_1");
			builder.put(grammarAccess.getToDoCAccess().getAttachAssignment_17_2(), "rule__ToDoC__AttachAssignment_17_2");
			builder.put(grammarAccess.getToDoCAccess().getAttachAssignment_17_3_1(), "rule__ToDoC__AttachAssignment_17_3_1");
			builder.put(grammarAccess.getToDoCAccess().getAttendeeAssignment_18_2(), "rule__ToDoC__AttendeeAssignment_18_2");
			builder.put(grammarAccess.getToDoCAccess().getAttendeeAssignment_18_3_1(), "rule__ToDoC__AttendeeAssignment_18_3_1");
			builder.put(grammarAccess.getToDoCAccess().getCategoriesAssignment_19_2(), "rule__ToDoC__CategoriesAssignment_19_2");
			builder.put(grammarAccess.getToDoCAccess().getCategoriesAssignment_19_3_1(), "rule__ToDoC__CategoriesAssignment_19_3_1");
			builder.put(grammarAccess.getToDoCAccess().getCommentAssignment_20_2(), "rule__ToDoC__CommentAssignment_20_2");
			builder.put(grammarAccess.getToDoCAccess().getCommentAssignment_20_3_1(), "rule__ToDoC__CommentAssignment_20_3_1");
			builder.put(grammarAccess.getToDoCAccess().getContactAssignment_21_2(), "rule__ToDoC__ContactAssignment_21_2");
			builder.put(grammarAccess.getToDoCAccess().getContactAssignment_21_3_1(), "rule__ToDoC__ContactAssignment_21_3_1");
			builder.put(grammarAccess.getToDoCAccess().getExdateAssignment_22_2(), "rule__ToDoC__ExdateAssignment_22_2");
			builder.put(grammarAccess.getToDoCAccess().getExdateAssignment_22_3_1(), "rule__ToDoC__ExdateAssignment_22_3_1");
			builder.put(grammarAccess.getToDoCAccess().getRstatusAssignment_23_2(), "rule__ToDoC__RstatusAssignment_23_2");
			builder.put(grammarAccess.getToDoCAccess().getRstatusAssignment_23_3_1(), "rule__ToDoC__RstatusAssignment_23_3_1");
			builder.put(grammarAccess.getToDoCAccess().getRelatedAssignment_24_2(), "rule__ToDoC__RelatedAssignment_24_2");
			builder.put(grammarAccess.getToDoCAccess().getRelatedAssignment_24_3_1(), "rule__ToDoC__RelatedAssignment_24_3_1");
			builder.put(grammarAccess.getToDoCAccess().getResourcesAssignment_25_2(), "rule__ToDoC__ResourcesAssignment_25_2");
			builder.put(grammarAccess.getToDoCAccess().getResourcesAssignment_25_3_1(), "rule__ToDoC__ResourcesAssignment_25_3_1");
			builder.put(grammarAccess.getToDoCAccess().getRdateAssignment_26_2(), "rule__ToDoC__RdateAssignment_26_2");
			builder.put(grammarAccess.getToDoCAccess().getRdateAssignment_26_3_1(), "rule__ToDoC__RdateAssignment_26_3_1");
			builder.put(grammarAccess.getToDoCAccess().getX_propAssignment_27_2(), "rule__ToDoC__X_propAssignment_27_2");
			builder.put(grammarAccess.getToDoCAccess().getX_propAssignment_27_3_1(), "rule__ToDoC__X_propAssignment_27_3_1");
			builder.put(grammarAccess.getToDoCAccess().getIana_propAssignment_28_2(), "rule__ToDoC__Iana_propAssignment_28_2");
			builder.put(grammarAccess.getToDoCAccess().getIana_propAssignment_28_3_1(), "rule__ToDoC__Iana_propAssignment_28_3_1");
			builder.put(grammarAccess.getToDoCAccess().getDescriptionAssignment_29_1(), "rule__ToDoC__DescriptionAssignment_29_1");
			builder.put(grammarAccess.getToDoCAccess().getCompletedAssignment_30_1(), "rule__ToDoC__CompletedAssignment_30_1");
			builder.put(grammarAccess.getToDoCAccess().getPriorityAssignment_31_1(), "rule__ToDoC__PriorityAssignment_31_1");
			builder.put(grammarAccess.getToDoCAccess().getGeoAssignment_32_1(), "rule__ToDoC__GeoAssignment_32_1");
			builder.put(grammarAccess.getToDoCAccess().getLocationAssignment_33_1(), "rule__ToDoC__LocationAssignment_33_1");
			builder.put(grammarAccess.getToDoCAccess().getDtendAssignment_34_1(), "rule__ToDoC__DtendAssignment_34_1");
			builder.put(grammarAccess.getToDoCAccess().getAlarmcAssignment_35_2(), "rule__ToDoC__AlarmcAssignment_35_2");
			builder.put(grammarAccess.getToDoCAccess().getAlarmcAssignment_35_3_1(), "rule__ToDoC__AlarmcAssignment_35_3_1");
			builder.put(grammarAccess.getJournalCAccess().getDtstampAssignment_3(), "rule__JournalC__DtstampAssignment_3");
			builder.put(grammarAccess.getJournalCAccess().getUidAssignment_5(), "rule__JournalC__UidAssignment_5");
			builder.put(grammarAccess.getJournalCAccess().getDtstartAssignment_6_1(), "rule__JournalC__DtstartAssignment_6_1");
			builder.put(grammarAccess.getJournalCAccess().getClassAssignment_7_1(), "rule__JournalC__ClassAssignment_7_1");
			builder.put(grammarAccess.getJournalCAccess().getCreatedAssignment_8_1(), "rule__JournalC__CreatedAssignment_8_1");
			builder.put(grammarAccess.getJournalCAccess().getLast_modAssignment_9_1(), "rule__JournalC__Last_modAssignment_9_1");
			builder.put(grammarAccess.getJournalCAccess().getOrganizerAssignment_10_1(), "rule__JournalC__OrganizerAssignment_10_1");
			builder.put(grammarAccess.getJournalCAccess().getSeqAssignment_11_1(), "rule__JournalC__SeqAssignment_11_1");
			builder.put(grammarAccess.getJournalCAccess().getStatusAssignment_12_1(), "rule__JournalC__StatusAssignment_12_1");
			builder.put(grammarAccess.getJournalCAccess().getSummaryAssignment_13_1(), "rule__JournalC__SummaryAssignment_13_1");
			builder.put(grammarAccess.getJournalCAccess().getUrlAssignment_14_1(), "rule__JournalC__UrlAssignment_14_1");
			builder.put(grammarAccess.getJournalCAccess().getRecuridAssignment_15_1(), "rule__JournalC__RecuridAssignment_15_1");
			builder.put(grammarAccess.getJournalCAccess().getRruleAssignment_16_2(), "rule__JournalC__RruleAssignment_16_2");
			builder.put(grammarAccess.getJournalCAccess().getRruleAssignment_16_3_1(), "rule__JournalC__RruleAssignment_16_3_1");
			builder.put(grammarAccess.getJournalCAccess().getAttachAssignment_17_2(), "rule__JournalC__AttachAssignment_17_2");
			builder.put(grammarAccess.getJournalCAccess().getAttachAssignment_17_3_1(), "rule__JournalC__AttachAssignment_17_3_1");
			builder.put(grammarAccess.getJournalCAccess().getAttendeeAssignment_18_2(), "rule__JournalC__AttendeeAssignment_18_2");
			builder.put(grammarAccess.getJournalCAccess().getAttendeeAssignment_18_3_1(), "rule__JournalC__AttendeeAssignment_18_3_1");
			builder.put(grammarAccess.getJournalCAccess().getCategoriesAssignment_19_2(), "rule__JournalC__CategoriesAssignment_19_2");
			builder.put(grammarAccess.getJournalCAccess().getCategoriesAssignment_19_3_1(), "rule__JournalC__CategoriesAssignment_19_3_1");
			builder.put(grammarAccess.getJournalCAccess().getCommentAssignment_20_2(), "rule__JournalC__CommentAssignment_20_2");
			builder.put(grammarAccess.getJournalCAccess().getCommentAssignment_20_3_1(), "rule__JournalC__CommentAssignment_20_3_1");
			builder.put(grammarAccess.getJournalCAccess().getContactAssignment_21_2(), "rule__JournalC__ContactAssignment_21_2");
			builder.put(grammarAccess.getJournalCAccess().getContactAssignment_21_3_1(), "rule__JournalC__ContactAssignment_21_3_1");
			builder.put(grammarAccess.getJournalCAccess().getExdateAssignment_22_2(), "rule__JournalC__ExdateAssignment_22_2");
			builder.put(grammarAccess.getJournalCAccess().getExdateAssignment_22_3_1(), "rule__JournalC__ExdateAssignment_22_3_1");
			builder.put(grammarAccess.getJournalCAccess().getRstatusAssignment_23_2(), "rule__JournalC__RstatusAssignment_23_2");
			builder.put(grammarAccess.getJournalCAccess().getRstatusAssignment_23_3_1(), "rule__JournalC__RstatusAssignment_23_3_1");
			builder.put(grammarAccess.getJournalCAccess().getRelatedAssignment_24_2(), "rule__JournalC__RelatedAssignment_24_2");
			builder.put(grammarAccess.getJournalCAccess().getRelatedAssignment_24_3_1(), "rule__JournalC__RelatedAssignment_24_3_1");
			builder.put(grammarAccess.getJournalCAccess().getResourcesAssignment_25_2(), "rule__JournalC__ResourcesAssignment_25_2");
			builder.put(grammarAccess.getJournalCAccess().getResourcesAssignment_25_3_1(), "rule__JournalC__ResourcesAssignment_25_3_1");
			builder.put(grammarAccess.getJournalCAccess().getRdateAssignment_26_2(), "rule__JournalC__RdateAssignment_26_2");
			builder.put(grammarAccess.getJournalCAccess().getRdateAssignment_26_3_1(), "rule__JournalC__RdateAssignment_26_3_1");
			builder.put(grammarAccess.getJournalCAccess().getX_propAssignment_27_2(), "rule__JournalC__X_propAssignment_27_2");
			builder.put(grammarAccess.getJournalCAccess().getX_propAssignment_27_3_1(), "rule__JournalC__X_propAssignment_27_3_1");
			builder.put(grammarAccess.getJournalCAccess().getIana_propAssignment_28_2(), "rule__JournalC__Iana_propAssignment_28_2");
			builder.put(grammarAccess.getJournalCAccess().getIana_propAssignment_28_3_1(), "rule__JournalC__Iana_propAssignment_28_3_1");
			builder.put(grammarAccess.getJournalCAccess().getDescriptionAssignment_29_1(), "rule__JournalC__DescriptionAssignment_29_1");
			builder.put(grammarAccess.getVacationCAccess().getDtstampAssignment_3(), "rule__VacationC__DtstampAssignment_3");
			builder.put(grammarAccess.getVacationCAccess().getUidAssignment_5(), "rule__VacationC__UidAssignment_5");
			builder.put(grammarAccess.getVacationCAccess().getDtstartAssignment_6_1(), "rule__VacationC__DtstartAssignment_6_1");
			builder.put(grammarAccess.getVacationCAccess().getOrganizerAssignment_7_1(), "rule__VacationC__OrganizerAssignment_7_1");
			builder.put(grammarAccess.getVacationCAccess().getUrlAssignment_8_1(), "rule__VacationC__UrlAssignment_8_1");
			builder.put(grammarAccess.getVacationCAccess().getContactAssignment_9_1(), "rule__VacationC__ContactAssignment_9_1");
			builder.put(grammarAccess.getVacationCAccess().getDtendAssignment_10_1(), "rule__VacationC__DtendAssignment_10_1");
			builder.put(grammarAccess.getVacationCAccess().getAttendeeAssignment_11_2(), "rule__VacationC__AttendeeAssignment_11_2");
			builder.put(grammarAccess.getVacationCAccess().getAttendeeAssignment_11_3_1(), "rule__VacationC__AttendeeAssignment_11_3_1");
			builder.put(grammarAccess.getVacationCAccess().getCommentAssignment_12_2(), "rule__VacationC__CommentAssignment_12_2");
			builder.put(grammarAccess.getVacationCAccess().getCommentAssignment_12_3_1(), "rule__VacationC__CommentAssignment_12_3_1");
			builder.put(grammarAccess.getVacationCAccess().getFreebusyAssignment_13_2(), "rule__VacationC__FreebusyAssignment_13_2");
			builder.put(grammarAccess.getVacationCAccess().getFreebusyAssignment_13_3_1(), "rule__VacationC__FreebusyAssignment_13_3_1");
			builder.put(grammarAccess.getVacationCAccess().getRstatusAssignment_14_2(), "rule__VacationC__RstatusAssignment_14_2");
			builder.put(grammarAccess.getVacationCAccess().getRstatusAssignment_14_3_1(), "rule__VacationC__RstatusAssignment_14_3_1");
			builder.put(grammarAccess.getVacationCAccess().getX_propAssignment_15_2(), "rule__VacationC__X_propAssignment_15_2");
			builder.put(grammarAccess.getVacationCAccess().getX_propAssignment_15_3_1(), "rule__VacationC__X_propAssignment_15_3_1");
			builder.put(grammarAccess.getVacationCAccess().getIana_propAssignment_16_2(), "rule__VacationC__Iana_propAssignment_16_2");
			builder.put(grammarAccess.getVacationCAccess().getIana_propAssignment_16_3_1(), "rule__VacationC__Iana_propAssignment_16_3_1");
			builder.put(grammarAccess.getTimeZoneCAccess().getTzidAssignment_3(), "rule__TimeZoneC__TzidAssignment_3");
			builder.put(grammarAccess.getTimeZoneCAccess().getLast_modAssignment_4_1(), "rule__TimeZoneC__Last_modAssignment_4_1");
			builder.put(grammarAccess.getTimeZoneCAccess().getTzurlAssignment_5_1(), "rule__TimeZoneC__TzurlAssignment_5_1");
			builder.put(grammarAccess.getTimeZoneCAccess().getX_propAssignment_6_2(), "rule__TimeZoneC__X_propAssignment_6_2");
			builder.put(grammarAccess.getTimeZoneCAccess().getX_propAssignment_6_3_1(), "rule__TimeZoneC__X_propAssignment_6_3_1");
			builder.put(grammarAccess.getTimeZoneCAccess().getIana_propAssignment_7_2(), "rule__TimeZoneC__Iana_propAssignment_7_2");
			builder.put(grammarAccess.getTimeZoneCAccess().getIana_propAssignment_7_3_1(), "rule__TimeZoneC__Iana_propAssignment_7_3_1");
			builder.put(grammarAccess.getTimeZoneCAccess().getStandardcAssignment_8_2(), "rule__TimeZoneC__StandardcAssignment_8_2");
			builder.put(grammarAccess.getTimeZoneCAccess().getStandardcAssignment_8_3_1(), "rule__TimeZoneC__StandardcAssignment_8_3_1");
			builder.put(grammarAccess.getTimeZoneCAccess().getDaylightcAssignment_9_2(), "rule__TimeZoneC__DaylightcAssignment_9_2");
			builder.put(grammarAccess.getTimeZoneCAccess().getDaylightcAssignment_9_3_1(), "rule__TimeZoneC__DaylightcAssignment_9_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
