/*
 * generated by Xtext 2.22.0
 */
package xCalendar.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import xCalendar.ide.contentassist.antlr.internal.InternalMyDslParser;
import xCalendar.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getComponentAccess().getAlternatives(), "rule__Component__Alternatives");
			builder.put(grammarAccess.getAlarmTypeAccess().getAlternatives(), "rule__AlarmType__Alternatives");
			builder.put(grammarAccess.getDateTAccess().getAlternatives_5_2(), "rule__DateT__Alternatives_5_2");
			builder.put(grammarAccess.getDateTAccess().getAlternatives_5_3_1(), "rule__DateT__Alternatives_5_3_1");
			builder.put(grammarAccess.getDateTAccess().getAlternatives_5_4_2(), "rule__DateT__Alternatives_5_4_2");
			builder.put(grammarAccess.getClassificationAccess().getAlternatives(), "rule__Classification__Alternatives");
			builder.put(grammarAccess.getStatusAccess().getAlternatives(), "rule__Status__Alternatives");
			builder.put(grammarAccess.getEventStatusAccess().getAlternatives(), "rule__EventStatus__Alternatives");
			builder.put(grammarAccess.getDayNameAccess().getAlternatives(), "rule__DayName__Alternatives");
			builder.put(grammarAccess.getICalFormatAccess().getGroup(), "rule__ICalFormat__Group__0");
			builder.put(grammarAccess.getDateTAccess().getGroup(), "rule__DateT__Group__0");
			builder.put(grammarAccess.getDateTAccess().getGroup_5(), "rule__DateT__Group_5__0");
			builder.put(grammarAccess.getDateTAccess().getGroup_5_3(), "rule__DateT__Group_5_3__0");
			builder.put(grammarAccess.getDateTAccess().getGroup_5_4(), "rule__DateT__Group_5_4__0");
			builder.put(grammarAccess.getCalendarAccess().getGroup(), "rule__Calendar__Group__0");
			builder.put(grammarAccess.getCalendarAccess().getGroup_2(), "rule__Calendar__Group_2__0");
			builder.put(grammarAccess.getCalendarAccess().getGroup_3(), "rule__Calendar__Group_3__0");
			builder.put(grammarAccess.getCalendarAccess().getGroup_4(), "rule__Calendar__Group_4__0");
			builder.put(grammarAccess.getCalendarAccess().getGroup_5(), "rule__Calendar__Group_5__0");
			builder.put(grammarAccess.getEventCAccess().getGroup(), "rule__EventC__Group__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_0(), "rule__EventC__Group_2_0__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_1(), "rule__EventC__Group_2_1__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_2(), "rule__EventC__Group_2_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_3(), "rule__EventC__Group_2_3__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_4(), "rule__EventC__Group_2_4__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_5(), "rule__EventC__Group_2_5__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_5_2(), "rule__EventC__Group_2_5_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_6(), "rule__EventC__Group_2_6__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_6_2(), "rule__EventC__Group_2_6_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_7(), "rule__EventC__Group_2_7__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_7_2(), "rule__EventC__Group_2_7_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_8(), "rule__EventC__Group_2_8__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_8_2(), "rule__EventC__Group_2_8_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_9(), "rule__EventC__Group_2_9__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_9_2(), "rule__EventC__Group_2_9_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_10(), "rule__EventC__Group_2_10__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_10_2(), "rule__EventC__Group_2_10_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_11(), "rule__EventC__Group_2_11__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_11_2(), "rule__EventC__Group_2_11_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_12(), "rule__EventC__Group_2_12__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_12_2(), "rule__EventC__Group_2_12_2__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_13(), "rule__EventC__Group_2_13__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_14(), "rule__EventC__Group_2_14__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_15(), "rule__EventC__Group_2_15__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_16(), "rule__EventC__Group_2_16__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_17(), "rule__EventC__Group_2_17__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_18(), "rule__EventC__Group_2_18__0");
			builder.put(grammarAccess.getEventCAccess().getGroup_2_18_2(), "rule__EventC__Group_2_18_2__0");
			builder.put(grammarAccess.getAlarmCAccess().getGroup(), "rule__AlarmC__Group__0");
			builder.put(grammarAccess.getAlarmCAccess().getGroup_2_0(), "rule__AlarmC__Group_2_0__0");
			builder.put(grammarAccess.getAlarmCAccess().getGroup_2_1(), "rule__AlarmC__Group_2_1__0");
			builder.put(grammarAccess.getAlarmCAccess().getGroup_2_2(), "rule__AlarmC__Group_2_2__0");
			builder.put(grammarAccess.getAlarmCAccess().getGroup_2_3(), "rule__AlarmC__Group_2_3__0");
			builder.put(grammarAccess.getAlarmCAccess().getGroup_2_4(), "rule__AlarmC__Group_2_4__0");
			builder.put(grammarAccess.getAlarmCAccess().getGroup_2_5(), "rule__AlarmC__Group_2_5__0");
			builder.put(grammarAccess.getTzpropAccess().getGroup(), "rule__Tzprop__Group__0");
			builder.put(grammarAccess.getTzpropAccess().getGroup_2_0(), "rule__Tzprop__Group_2_0__0");
			builder.put(grammarAccess.getTzpropAccess().getGroup_2_1(), "rule__Tzprop__Group_2_1__0");
			builder.put(grammarAccess.getTzpropAccess().getGroup_2_2(), "rule__Tzprop__Group_2_2__0");
			builder.put(grammarAccess.getTzpropAccess().getGroup_2_3(), "rule__Tzprop__Group_2_3__0");
			builder.put(grammarAccess.getTzpropAccess().getGroup_2_4(), "rule__Tzprop__Group_2_4__0");
			builder.put(grammarAccess.getTzpropAccess().getGroup_2_4_3(), "rule__Tzprop__Group_2_4_3__0");
			builder.put(grammarAccess.getTzpropOptionalAccess().getGroup(), "rule__TzpropOptional__Group__0");
			builder.put(grammarAccess.getTzpropOptionalAccess().getGroup_3_0(), "rule__TzpropOptional__Group_3_0__0");
			builder.put(grammarAccess.getTzpropOptionalAccess().getGroup_3_1(), "rule__TzpropOptional__Group_3_1__0");
			builder.put(grammarAccess.getTzpropOptionalAccess().getGroup_3_2(), "rule__TzpropOptional__Group_3_2__0");
			builder.put(grammarAccess.getTzpropOptionalAccess().getGroup_3_3(), "rule__TzpropOptional__Group_3_3__0");
			builder.put(grammarAccess.getTzpropOptionalAccess().getGroup_3_4(), "rule__TzpropOptional__Group_3_4__0");
			builder.put(grammarAccess.getComponentAlarmTimeAccess().getGroup(), "rule__ComponentAlarmTime__Group__0");
			builder.put(grammarAccess.getComponentAlarmTimeAccess().getGroup_3_0(), "rule__ComponentAlarmTime__Group_3_0__0");
			builder.put(grammarAccess.getComponentAlarmTimeAccess().getGroup_3_1(), "rule__ComponentAlarmTime__Group_3_1__0");
			builder.put(grammarAccess.getComponentAlarmAudioPropertyAccess().getGroup(), "rule__ComponentAlarmAudioProperty__Group__0");
			builder.put(grammarAccess.getComponentAlarmAudioPropertyAccess().getGroup_3(), "rule__ComponentAlarmAudioProperty__Group_3__0");
			builder.put(grammarAccess.getComponentAlarmDispPropertyAccess().getGroup(), "rule__ComponentAlarmDispProperty__Group__0");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getGroup(), "rule__ComponentAlarmEmailProperty__Group__0");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getGroup_2_0(), "rule__ComponentAlarmEmailProperty__Group_2_0__0");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getGroup_2_0_3(), "rule__ComponentAlarmEmailProperty__Group_2_0_3__0");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getGroup_2_1(), "rule__ComponentAlarmEmailProperty__Group_2_1__0");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getGroup_2_2(), "rule__ComponentAlarmEmailProperty__Group_2_2__0");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getGroup_2_2_3(), "rule__ComponentAlarmEmailProperty__Group_2_2_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup(), "rule__ToDoC__Group__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_0(), "rule__ToDoC__Group_2_0__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_1(), "rule__ToDoC__Group_2_1__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_2(), "rule__ToDoC__Group_2_2__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_3(), "rule__ToDoC__Group_2_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_4(), "rule__ToDoC__Group_2_4__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_5(), "rule__ToDoC__Group_2_5__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_6(), "rule__ToDoC__Group_2_6__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_7(), "rule__ToDoC__Group_2_7__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_8(), "rule__ToDoC__Group_2_8__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_9(), "rule__ToDoC__Group_2_9__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_10(), "rule__ToDoC__Group_2_10__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_11(), "rule__ToDoC__Group_2_11__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_12(), "rule__ToDoC__Group_2_12__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_13(), "rule__ToDoC__Group_2_13__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_13_3(), "rule__ToDoC__Group_2_13_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_14(), "rule__ToDoC__Group_2_14__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_14_3(), "rule__ToDoC__Group_2_14_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_15(), "rule__ToDoC__Group_2_15__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_15_3(), "rule__ToDoC__Group_2_15_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_16(), "rule__ToDoC__Group_2_16__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_16_3(), "rule__ToDoC__Group_2_16_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_17(), "rule__ToDoC__Group_2_17__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_17_3(), "rule__ToDoC__Group_2_17_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_18(), "rule__ToDoC__Group_2_18__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_18_3(), "rule__ToDoC__Group_2_18_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_19(), "rule__ToDoC__Group_2_19__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_19_3(), "rule__ToDoC__Group_2_19_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_20(), "rule__ToDoC__Group_2_20__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_20_3(), "rule__ToDoC__Group_2_20_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_21(), "rule__ToDoC__Group_2_21__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_21_3(), "rule__ToDoC__Group_2_21_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_22(), "rule__ToDoC__Group_2_22__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_22_3(), "rule__ToDoC__Group_2_22_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_23(), "rule__ToDoC__Group_2_23__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_23_3(), "rule__ToDoC__Group_2_23_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_24(), "rule__ToDoC__Group_2_24__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_24_3(), "rule__ToDoC__Group_2_24_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_25(), "rule__ToDoC__Group_2_25__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_25_3(), "rule__ToDoC__Group_2_25_3__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_26(), "rule__ToDoC__Group_2_26__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_27(), "rule__ToDoC__Group_2_27__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_28(), "rule__ToDoC__Group_2_28__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_29(), "rule__ToDoC__Group_2_29__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_30(), "rule__ToDoC__Group_2_30__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_31(), "rule__ToDoC__Group_2_31__0");
			builder.put(grammarAccess.getToDoCAccess().getGroup_2_31_2(), "rule__ToDoC__Group_2_31_2__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup(), "rule__JournalC__Group__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_0(), "rule__JournalC__Group_2_0__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_1(), "rule__JournalC__Group_2_1__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_2(), "rule__JournalC__Group_2_2__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_3(), "rule__JournalC__Group_2_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_4(), "rule__JournalC__Group_2_4__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_5(), "rule__JournalC__Group_2_5__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_6(), "rule__JournalC__Group_2_6__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_7(), "rule__JournalC__Group_2_7__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_8(), "rule__JournalC__Group_2_8__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_9(), "rule__JournalC__Group_2_9__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_10(), "rule__JournalC__Group_2_10__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_11(), "rule__JournalC__Group_2_11__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_11_3(), "rule__JournalC__Group_2_11_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_12(), "rule__JournalC__Group_2_12__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_12_3(), "rule__JournalC__Group_2_12_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_13(), "rule__JournalC__Group_2_13__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_13_3(), "rule__JournalC__Group_2_13_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_14(), "rule__JournalC__Group_2_14__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_14_3(), "rule__JournalC__Group_2_14_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_15(), "rule__JournalC__Group_2_15__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_15_3(), "rule__JournalC__Group_2_15_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_16(), "rule__JournalC__Group_2_16__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_16_3(), "rule__JournalC__Group_2_16_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_17(), "rule__JournalC__Group_2_17__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_17_3(), "rule__JournalC__Group_2_17_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_18(), "rule__JournalC__Group_2_18__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_18_3(), "rule__JournalC__Group_2_18_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_19(), "rule__JournalC__Group_2_19__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_19_3(), "rule__JournalC__Group_2_19_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_20(), "rule__JournalC__Group_2_20__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_20_3(), "rule__JournalC__Group_2_20_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_21(), "rule__JournalC__Group_2_21__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_21_3(), "rule__JournalC__Group_2_21_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_22(), "rule__JournalC__Group_2_22__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_22_3(), "rule__JournalC__Group_2_22_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_23(), "rule__JournalC__Group_2_23__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_23_3(), "rule__JournalC__Group_2_23_3__0");
			builder.put(grammarAccess.getJournalCAccess().getGroup_2_24(), "rule__JournalC__Group_2_24__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup(), "rule__VacationC__Group__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_0(), "rule__VacationC__Group_2_0__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_1(), "rule__VacationC__Group_2_1__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_2(), "rule__VacationC__Group_2_2__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_3(), "rule__VacationC__Group_2_3__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_4(), "rule__VacationC__Group_2_4__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_5(), "rule__VacationC__Group_2_5__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_6(), "rule__VacationC__Group_2_6__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_6_3(), "rule__VacationC__Group_2_6_3__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_7(), "rule__VacationC__Group_2_7__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_7_3(), "rule__VacationC__Group_2_7_3__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_8(), "rule__VacationC__Group_2_8__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_8_3(), "rule__VacationC__Group_2_8_3__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_9(), "rule__VacationC__Group_2_9__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_9_3(), "rule__VacationC__Group_2_9_3__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_10(), "rule__VacationC__Group_2_10__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_10_3(), "rule__VacationC__Group_2_10_3__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_11(), "rule__VacationC__Group_2_11__0");
			builder.put(grammarAccess.getVacationCAccess().getGroup_2_11_3(), "rule__VacationC__Group_2_11_3__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup(), "rule__TimeZoneC__Group__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_2_0(), "rule__TimeZoneC__Group_2_0__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_2_1(), "rule__TimeZoneC__Group_2_1__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_2_2(), "rule__TimeZoneC__Group_2_2__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_2_3(), "rule__TimeZoneC__Group_2_3__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_2_3_3(), "rule__TimeZoneC__Group_2_3_3__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_2_4(), "rule__TimeZoneC__Group_2_4__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_2_4_3(), "rule__TimeZoneC__Group_2_4_3__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_2_5(), "rule__TimeZoneC__Group_2_5__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_2_5_3(), "rule__TimeZoneC__Group_2_5_3__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_2_6(), "rule__TimeZoneC__Group_2_6__0");
			builder.put(grammarAccess.getTimeZoneCAccess().getGroup_2_6_3(), "rule__TimeZoneC__Group_2_6_3__0");
			builder.put(grammarAccess.getICalFormatAccess().getFileNameAssignment_1(), "rule__ICalFormat__FileNameAssignment_1");
			builder.put(grammarAccess.getICalFormatAccess().getCalendarAssignment_2(), "rule__ICalFormat__CalendarAssignment_2");
			builder.put(grammarAccess.getDateTAccess().getDay_nameAssignment_0(), "rule__DateT__Day_nameAssignment_0");
			builder.put(grammarAccess.getDateTAccess().getDayAssignment_1(), "rule__DateT__DayAssignment_1");
			builder.put(grammarAccess.getDateTAccess().getMonthAssignment_2(), "rule__DateT__MonthAssignment_2");
			builder.put(grammarAccess.getDateTAccess().getMonth_nameAssignment_3(), "rule__DateT__Month_nameAssignment_3");
			builder.put(grammarAccess.getDateTAccess().getYearAssignment_4(), "rule__DateT__YearAssignment_4");
			builder.put(grammarAccess.getDateTAccess().getHoursAssignment_5_1(), "rule__DateT__HoursAssignment_5_1");
			builder.put(grammarAccess.getDateTAccess().getMinutesAssignment_5_3_0(), "rule__DateT__MinutesAssignment_5_3_0");
			builder.put(grammarAccess.getDateTAccess().getSecondsAssignment_5_4_1(), "rule__DateT__SecondsAssignment_5_4_1");
			builder.put(grammarAccess.getCalendarAccess().getVersionAssignment_2_1(), "rule__Calendar__VersionAssignment_2_1");
			builder.put(grammarAccess.getCalendarAccess().getProdidAssignment_3_1(), "rule__Calendar__ProdidAssignment_3_1");
			builder.put(grammarAccess.getCalendarAccess().getMethodAssignment_4_1(), "rule__Calendar__MethodAssignment_4_1");
			builder.put(grammarAccess.getCalendarAccess().getCalscaleAssignment_5_1(), "rule__Calendar__CalscaleAssignment_5_1");
			builder.put(grammarAccess.getCalendarAccess().getComponentAssignment_6(), "rule__Calendar__ComponentAssignment_6");
			builder.put(grammarAccess.getEventCAccess().getDtstartAssignment_2_0_1(), "rule__EventC__DtstartAssignment_2_0_1");
			builder.put(grammarAccess.getEventCAccess().getUidAssignment_2_1_1(), "rule__EventC__UidAssignment_2_1_1");
			builder.put(grammarAccess.getEventCAccess().getOrganizerAssignment_2_2_1(), "rule__EventC__OrganizerAssignment_2_2_1");
			builder.put(grammarAccess.getEventCAccess().getSummaryAssignment_2_3_1(), "rule__EventC__SummaryAssignment_2_3_1");
			builder.put(grammarAccess.getEventCAccess().getUrlAssignment_2_4_1(), "rule__EventC__UrlAssignment_2_4_1");
			builder.put(grammarAccess.getEventCAccess().getAttachAssignment_2_5_1(), "rule__EventC__AttachAssignment_2_5_1");
			builder.put(grammarAccess.getEventCAccess().getAttachAssignment_2_5_2_1(), "rule__EventC__AttachAssignment_2_5_2_1");
			builder.put(grammarAccess.getEventCAccess().getAttendeeAssignment_2_6_1(), "rule__EventC__AttendeeAssignment_2_6_1");
			builder.put(grammarAccess.getEventCAccess().getAttendeeAssignment_2_6_2_1(), "rule__EventC__AttendeeAssignment_2_6_2_1");
			builder.put(grammarAccess.getEventCAccess().getCategoriesAssignment_2_7_1(), "rule__EventC__CategoriesAssignment_2_7_1");
			builder.put(grammarAccess.getEventCAccess().getCategoriesAssignment_2_7_2_1(), "rule__EventC__CategoriesAssignment_2_7_2_1");
			builder.put(grammarAccess.getEventCAccess().getCommentAssignment_2_8_1(), "rule__EventC__CommentAssignment_2_8_1");
			builder.put(grammarAccess.getEventCAccess().getCommentAssignment_2_8_2_1(), "rule__EventC__CommentAssignment_2_8_2_1");
			builder.put(grammarAccess.getEventCAccess().getContactAssignment_2_9_1(), "rule__EventC__ContactAssignment_2_9_1");
			builder.put(grammarAccess.getEventCAccess().getContactAssignment_2_9_2_1(), "rule__EventC__ContactAssignment_2_9_2_1");
			builder.put(grammarAccess.getEventCAccess().getRstatusAssignment_2_10_1(), "rule__EventC__RstatusAssignment_2_10_1");
			builder.put(grammarAccess.getEventCAccess().getRstatusAssignment_2_10_2_1(), "rule__EventC__RstatusAssignment_2_10_2_1");
			builder.put(grammarAccess.getEventCAccess().getRelatedAssignment_2_11_1(), "rule__EventC__RelatedAssignment_2_11_1");
			builder.put(grammarAccess.getEventCAccess().getRelatedAssignment_2_11_2_1(), "rule__EventC__RelatedAssignment_2_11_2_1");
			builder.put(grammarAccess.getEventCAccess().getResourcesAssignment_2_12_1(), "rule__EventC__ResourcesAssignment_2_12_1");
			builder.put(grammarAccess.getEventCAccess().getResourcesAssignment_2_12_2_1(), "rule__EventC__ResourcesAssignment_2_12_2_1");
			builder.put(grammarAccess.getEventCAccess().getDescriptionAssignment_2_13_1(), "rule__EventC__DescriptionAssignment_2_13_1");
			builder.put(grammarAccess.getEventCAccess().getPriorityAssignment_2_14_1(), "rule__EventC__PriorityAssignment_2_14_1");
			builder.put(grammarAccess.getEventCAccess().getLocationAssignment_2_15_1(), "rule__EventC__LocationAssignment_2_15_1");
			builder.put(grammarAccess.getEventCAccess().getDtendAssignment_2_16_1(), "rule__EventC__DtendAssignment_2_16_1");
			builder.put(grammarAccess.getEventCAccess().getClassAssignment_2_17_1(), "rule__EventC__ClassAssignment_2_17_1");
			builder.put(grammarAccess.getEventCAccess().getAlarmcAssignment_2_18_1(), "rule__EventC__AlarmcAssignment_2_18_1");
			builder.put(grammarAccess.getEventCAccess().getAlarmcAssignment_2_18_2_1(), "rule__EventC__AlarmcAssignment_2_18_2_1");
			builder.put(grammarAccess.getAlarmCAccess().getActionAssignment_2_0_1(), "rule__AlarmC__ActionAssignment_2_0_1");
			builder.put(grammarAccess.getAlarmCAccess().getTriggerAssignment_2_1_1(), "rule__AlarmC__TriggerAssignment_2_1_1");
			builder.put(grammarAccess.getAlarmCAccess().getAttachAssignment_2_2_1(), "rule__AlarmC__AttachAssignment_2_2_1");
			builder.put(grammarAccess.getAlarmCAccess().getDescriptionAssignment_2_3_1(), "rule__AlarmC__DescriptionAssignment_2_3_1");
			builder.put(grammarAccess.getAlarmCAccess().getTypeAssignment_2_4_1(), "rule__AlarmC__TypeAssignment_2_4_1");
			builder.put(grammarAccess.getAlarmCAccess().getTimeAssignment_2_5_1(), "rule__AlarmC__TimeAssignment_2_5_1");
			builder.put(grammarAccess.getTzpropAccess().getDtstartAssignment_2_0_1(), "rule__Tzprop__DtstartAssignment_2_0_1");
			builder.put(grammarAccess.getTzpropAccess().getTzoffsetoAssignment_2_1_1(), "rule__Tzprop__TzoffsetoAssignment_2_1_1");
			builder.put(grammarAccess.getTzpropAccess().getTzoffsetfromAssignment_2_2_1(), "rule__Tzprop__TzoffsetfromAssignment_2_2_1");
			builder.put(grammarAccess.getTzpropAccess().getRruleAssignment_2_3_1(), "rule__Tzprop__RruleAssignment_2_3_1");
			builder.put(grammarAccess.getTzpropAccess().getOptAssignment_2_4_2(), "rule__Tzprop__OptAssignment_2_4_2");
			builder.put(grammarAccess.getTzpropAccess().getOptAssignment_2_4_3_1(), "rule__Tzprop__OptAssignment_2_4_3_1");
			builder.put(grammarAccess.getTzpropOptionalAccess().getCommentAssignment_3_0_1(), "rule__TzpropOptional__CommentAssignment_3_0_1");
			builder.put(grammarAccess.getTzpropOptionalAccess().getRdateAssignment_3_1_1(), "rule__TzpropOptional__RdateAssignment_3_1_1");
			builder.put(grammarAccess.getTzpropOptionalAccess().getTznameAssignment_3_2_1(), "rule__TzpropOptional__TznameAssignment_3_2_1");
			builder.put(grammarAccess.getTzpropOptionalAccess().getX_propAssignment_3_3_1(), "rule__TzpropOptional__X_propAssignment_3_3_1");
			builder.put(grammarAccess.getTzpropOptionalAccess().getIana_propAssignment_3_4_1(), "rule__TzpropOptional__Iana_propAssignment_3_4_1");
			builder.put(grammarAccess.getComponentAlarmTimeAccess().getDurationAssignment_3_0_1(), "rule__ComponentAlarmTime__DurationAssignment_3_0_1");
			builder.put(grammarAccess.getComponentAlarmTimeAccess().getRepeatAssignment_3_1_1(), "rule__ComponentAlarmTime__RepeatAssignment_3_1_1");
			builder.put(grammarAccess.getComponentAlarmAudioPropertyAccess().getAttachAssignment_3_1(), "rule__ComponentAlarmAudioProperty__AttachAssignment_3_1");
			builder.put(grammarAccess.getComponentAlarmDispPropertyAccess().getDescriptionAssignment_3(), "rule__ComponentAlarmDispProperty__DescriptionAssignment_3");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getAttendeeAssignment_2_0_2(), "rule__ComponentAlarmEmailProperty__AttendeeAssignment_2_0_2");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getAttendeeAssignment_2_0_3_1(), "rule__ComponentAlarmEmailProperty__AttendeeAssignment_2_0_3_1");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getDescriptionAssignment_2_1_1(), "rule__ComponentAlarmEmailProperty__DescriptionAssignment_2_1_1");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getAttachAssignment_2_2_2(), "rule__ComponentAlarmEmailProperty__AttachAssignment_2_2_2");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getAttachAssignment_2_2_3_1(), "rule__ComponentAlarmEmailProperty__AttachAssignment_2_2_3_1");
			builder.put(grammarAccess.getToDoCAccess().getDtstampAssignment_2_0_1(), "rule__ToDoC__DtstampAssignment_2_0_1");
			builder.put(grammarAccess.getToDoCAccess().getUidAssignment_2_1_1(), "rule__ToDoC__UidAssignment_2_1_1");
			builder.put(grammarAccess.getToDoCAccess().getDueAssignment_2_2_1(), "rule__ToDoC__DueAssignment_2_2_1");
			builder.put(grammarAccess.getToDoCAccess().getDtstartAssignment_2_3_1(), "rule__ToDoC__DtstartAssignment_2_3_1");
			builder.put(grammarAccess.getToDoCAccess().getClassAssignment_2_4_1(), "rule__ToDoC__ClassAssignment_2_4_1");
			builder.put(grammarAccess.getToDoCAccess().getCreatedAssignment_2_5_1(), "rule__ToDoC__CreatedAssignment_2_5_1");
			builder.put(grammarAccess.getToDoCAccess().getLast_modAssignment_2_6_1(), "rule__ToDoC__Last_modAssignment_2_6_1");
			builder.put(grammarAccess.getToDoCAccess().getOrganizerAssignment_2_7_1(), "rule__ToDoC__OrganizerAssignment_2_7_1");
			builder.put(grammarAccess.getToDoCAccess().getSeqAssignment_2_8_1(), "rule__ToDoC__SeqAssignment_2_8_1");
			builder.put(grammarAccess.getToDoCAccess().getStatusAssignment_2_9_1(), "rule__ToDoC__StatusAssignment_2_9_1");
			builder.put(grammarAccess.getToDoCAccess().getSummaryAssignment_2_10_1(), "rule__ToDoC__SummaryAssignment_2_10_1");
			builder.put(grammarAccess.getToDoCAccess().getUrlAssignment_2_11_1(), "rule__ToDoC__UrlAssignment_2_11_1");
			builder.put(grammarAccess.getToDoCAccess().getRecuridAssignment_2_12_1(), "rule__ToDoC__RecuridAssignment_2_12_1");
			builder.put(grammarAccess.getToDoCAccess().getRruleAssignment_2_13_2(), "rule__ToDoC__RruleAssignment_2_13_2");
			builder.put(grammarAccess.getToDoCAccess().getRruleAssignment_2_13_3_1(), "rule__ToDoC__RruleAssignment_2_13_3_1");
			builder.put(grammarAccess.getToDoCAccess().getAttachAssignment_2_14_2(), "rule__ToDoC__AttachAssignment_2_14_2");
			builder.put(grammarAccess.getToDoCAccess().getAttachAssignment_2_14_3_1(), "rule__ToDoC__AttachAssignment_2_14_3_1");
			builder.put(grammarAccess.getToDoCAccess().getAttendeeAssignment_2_15_2(), "rule__ToDoC__AttendeeAssignment_2_15_2");
			builder.put(grammarAccess.getToDoCAccess().getAttendeeAssignment_2_15_3_1(), "rule__ToDoC__AttendeeAssignment_2_15_3_1");
			builder.put(grammarAccess.getToDoCAccess().getCategoriesAssignment_2_16_2(), "rule__ToDoC__CategoriesAssignment_2_16_2");
			builder.put(grammarAccess.getToDoCAccess().getCategoriesAssignment_2_16_3_1(), "rule__ToDoC__CategoriesAssignment_2_16_3_1");
			builder.put(grammarAccess.getToDoCAccess().getCommentAssignment_2_17_2(), "rule__ToDoC__CommentAssignment_2_17_2");
			builder.put(grammarAccess.getToDoCAccess().getCommentAssignment_2_17_3_1(), "rule__ToDoC__CommentAssignment_2_17_3_1");
			builder.put(grammarAccess.getToDoCAccess().getContactAssignment_2_18_2(), "rule__ToDoC__ContactAssignment_2_18_2");
			builder.put(grammarAccess.getToDoCAccess().getContactAssignment_2_18_3_1(), "rule__ToDoC__ContactAssignment_2_18_3_1");
			builder.put(grammarAccess.getToDoCAccess().getExdateAssignment_2_19_2(), "rule__ToDoC__ExdateAssignment_2_19_2");
			builder.put(grammarAccess.getToDoCAccess().getExdateAssignment_2_19_3_1(), "rule__ToDoC__ExdateAssignment_2_19_3_1");
			builder.put(grammarAccess.getToDoCAccess().getRstatusAssignment_2_20_2(), "rule__ToDoC__RstatusAssignment_2_20_2");
			builder.put(grammarAccess.getToDoCAccess().getRstatusAssignment_2_20_3_1(), "rule__ToDoC__RstatusAssignment_2_20_3_1");
			builder.put(grammarAccess.getToDoCAccess().getRelatedAssignment_2_21_2(), "rule__ToDoC__RelatedAssignment_2_21_2");
			builder.put(grammarAccess.getToDoCAccess().getRelatedAssignment_2_21_3_1(), "rule__ToDoC__RelatedAssignment_2_21_3_1");
			builder.put(grammarAccess.getToDoCAccess().getResourcesAssignment_2_22_2(), "rule__ToDoC__ResourcesAssignment_2_22_2");
			builder.put(grammarAccess.getToDoCAccess().getResourcesAssignment_2_22_3_1(), "rule__ToDoC__ResourcesAssignment_2_22_3_1");
			builder.put(grammarAccess.getToDoCAccess().getRdateAssignment_2_23_2(), "rule__ToDoC__RdateAssignment_2_23_2");
			builder.put(grammarAccess.getToDoCAccess().getRdateAssignment_2_23_3_1(), "rule__ToDoC__RdateAssignment_2_23_3_1");
			builder.put(grammarAccess.getToDoCAccess().getX_propAssignment_2_24_2(), "rule__ToDoC__X_propAssignment_2_24_2");
			builder.put(grammarAccess.getToDoCAccess().getX_propAssignment_2_24_3_1(), "rule__ToDoC__X_propAssignment_2_24_3_1");
			builder.put(grammarAccess.getToDoCAccess().getIana_propAssignment_2_25_2(), "rule__ToDoC__Iana_propAssignment_2_25_2");
			builder.put(grammarAccess.getToDoCAccess().getIana_propAssignment_2_25_3_1(), "rule__ToDoC__Iana_propAssignment_2_25_3_1");
			builder.put(grammarAccess.getToDoCAccess().getDescriptionAssignment_2_26_1(), "rule__ToDoC__DescriptionAssignment_2_26_1");
			builder.put(grammarAccess.getToDoCAccess().getCompletedAssignment_2_27_1(), "rule__ToDoC__CompletedAssignment_2_27_1");
			builder.put(grammarAccess.getToDoCAccess().getPriorityAssignment_2_28_1(), "rule__ToDoC__PriorityAssignment_2_28_1");
			builder.put(grammarAccess.getToDoCAccess().getGeoAssignment_2_29_1(), "rule__ToDoC__GeoAssignment_2_29_1");
			builder.put(grammarAccess.getToDoCAccess().getLocationAssignment_2_30_1(), "rule__ToDoC__LocationAssignment_2_30_1");
			builder.put(grammarAccess.getToDoCAccess().getAlarmcAssignment_2_31_1(), "rule__ToDoC__AlarmcAssignment_2_31_1");
			builder.put(grammarAccess.getToDoCAccess().getAlarmcAssignment_2_31_2_1(), "rule__ToDoC__AlarmcAssignment_2_31_2_1");
			builder.put(grammarAccess.getJournalCAccess().getUidAssignment_2_0_1(), "rule__JournalC__UidAssignment_2_0_1");
			builder.put(grammarAccess.getJournalCAccess().getDtstartAssignment_2_1_1(), "rule__JournalC__DtstartAssignment_2_1_1");
			builder.put(grammarAccess.getJournalCAccess().getClassAssignment_2_2_1(), "rule__JournalC__ClassAssignment_2_2_1");
			builder.put(grammarAccess.getJournalCAccess().getCreatedAssignment_2_3_1(), "rule__JournalC__CreatedAssignment_2_3_1");
			builder.put(grammarAccess.getJournalCAccess().getLast_modAssignment_2_4_1(), "rule__JournalC__Last_modAssignment_2_4_1");
			builder.put(grammarAccess.getJournalCAccess().getOrganizerAssignment_2_5_1(), "rule__JournalC__OrganizerAssignment_2_5_1");
			builder.put(grammarAccess.getJournalCAccess().getSeqAssignment_2_6_1(), "rule__JournalC__SeqAssignment_2_6_1");
			builder.put(grammarAccess.getJournalCAccess().getStatusAssignment_2_7_1(), "rule__JournalC__StatusAssignment_2_7_1");
			builder.put(grammarAccess.getJournalCAccess().getSummaryAssignment_2_8_1(), "rule__JournalC__SummaryAssignment_2_8_1");
			builder.put(grammarAccess.getJournalCAccess().getUrlAssignment_2_9_1(), "rule__JournalC__UrlAssignment_2_9_1");
			builder.put(grammarAccess.getJournalCAccess().getRecuridAssignment_2_10_1(), "rule__JournalC__RecuridAssignment_2_10_1");
			builder.put(grammarAccess.getJournalCAccess().getRruleAssignment_2_11_2(), "rule__JournalC__RruleAssignment_2_11_2");
			builder.put(grammarAccess.getJournalCAccess().getRruleAssignment_2_11_3_1(), "rule__JournalC__RruleAssignment_2_11_3_1");
			builder.put(grammarAccess.getJournalCAccess().getAttachAssignment_2_12_2(), "rule__JournalC__AttachAssignment_2_12_2");
			builder.put(grammarAccess.getJournalCAccess().getAttachAssignment_2_12_3_1(), "rule__JournalC__AttachAssignment_2_12_3_1");
			builder.put(grammarAccess.getJournalCAccess().getAttendeeAssignment_2_13_2(), "rule__JournalC__AttendeeAssignment_2_13_2");
			builder.put(grammarAccess.getJournalCAccess().getAttendeeAssignment_2_13_3_1(), "rule__JournalC__AttendeeAssignment_2_13_3_1");
			builder.put(grammarAccess.getJournalCAccess().getCategoriesAssignment_2_14_2(), "rule__JournalC__CategoriesAssignment_2_14_2");
			builder.put(grammarAccess.getJournalCAccess().getCategoriesAssignment_2_14_3_1(), "rule__JournalC__CategoriesAssignment_2_14_3_1");
			builder.put(grammarAccess.getJournalCAccess().getCommentAssignment_2_15_2(), "rule__JournalC__CommentAssignment_2_15_2");
			builder.put(grammarAccess.getJournalCAccess().getCommentAssignment_2_15_3_1(), "rule__JournalC__CommentAssignment_2_15_3_1");
			builder.put(grammarAccess.getJournalCAccess().getContactAssignment_2_16_2(), "rule__JournalC__ContactAssignment_2_16_2");
			builder.put(grammarAccess.getJournalCAccess().getContactAssignment_2_16_3_1(), "rule__JournalC__ContactAssignment_2_16_3_1");
			builder.put(grammarAccess.getJournalCAccess().getExdateAssignment_2_17_2(), "rule__JournalC__ExdateAssignment_2_17_2");
			builder.put(grammarAccess.getJournalCAccess().getExdateAssignment_2_17_3_1(), "rule__JournalC__ExdateAssignment_2_17_3_1");
			builder.put(grammarAccess.getJournalCAccess().getRstatusAssignment_2_18_2(), "rule__JournalC__RstatusAssignment_2_18_2");
			builder.put(grammarAccess.getJournalCAccess().getRstatusAssignment_2_18_3_1(), "rule__JournalC__RstatusAssignment_2_18_3_1");
			builder.put(grammarAccess.getJournalCAccess().getRelatedAssignment_2_19_2(), "rule__JournalC__RelatedAssignment_2_19_2");
			builder.put(grammarAccess.getJournalCAccess().getRelatedAssignment_2_19_3_1(), "rule__JournalC__RelatedAssignment_2_19_3_1");
			builder.put(grammarAccess.getJournalCAccess().getResourcesAssignment_2_20_2(), "rule__JournalC__ResourcesAssignment_2_20_2");
			builder.put(grammarAccess.getJournalCAccess().getResourcesAssignment_2_20_3_1(), "rule__JournalC__ResourcesAssignment_2_20_3_1");
			builder.put(grammarAccess.getJournalCAccess().getRdateAssignment_2_21_2(), "rule__JournalC__RdateAssignment_2_21_2");
			builder.put(grammarAccess.getJournalCAccess().getRdateAssignment_2_21_3_1(), "rule__JournalC__RdateAssignment_2_21_3_1");
			builder.put(grammarAccess.getJournalCAccess().getX_propAssignment_2_22_2(), "rule__JournalC__X_propAssignment_2_22_2");
			builder.put(grammarAccess.getJournalCAccess().getX_propAssignment_2_22_3_1(), "rule__JournalC__X_propAssignment_2_22_3_1");
			builder.put(grammarAccess.getJournalCAccess().getIana_propAssignment_2_23_2(), "rule__JournalC__Iana_propAssignment_2_23_2");
			builder.put(grammarAccess.getJournalCAccess().getIana_propAssignment_2_23_3_1(), "rule__JournalC__Iana_propAssignment_2_23_3_1");
			builder.put(grammarAccess.getJournalCAccess().getDescriptionAssignment_2_24_1(), "rule__JournalC__DescriptionAssignment_2_24_1");
			builder.put(grammarAccess.getVacationCAccess().getUidAssignment_2_0_1(), "rule__VacationC__UidAssignment_2_0_1");
			builder.put(grammarAccess.getVacationCAccess().getDtstartAssignment_2_1_1(), "rule__VacationC__DtstartAssignment_2_1_1");
			builder.put(grammarAccess.getVacationCAccess().getOrganizerAssignment_2_2_1(), "rule__VacationC__OrganizerAssignment_2_2_1");
			builder.put(grammarAccess.getVacationCAccess().getUrlAssignment_2_3_1(), "rule__VacationC__UrlAssignment_2_3_1");
			builder.put(grammarAccess.getVacationCAccess().getContactAssignment_2_4_1(), "rule__VacationC__ContactAssignment_2_4_1");
			builder.put(grammarAccess.getVacationCAccess().getDtendAssignment_2_5_1(), "rule__VacationC__DtendAssignment_2_5_1");
			builder.put(grammarAccess.getVacationCAccess().getAttendeeAssignment_2_6_2(), "rule__VacationC__AttendeeAssignment_2_6_2");
			builder.put(grammarAccess.getVacationCAccess().getAttendeeAssignment_2_6_3_1(), "rule__VacationC__AttendeeAssignment_2_6_3_1");
			builder.put(grammarAccess.getVacationCAccess().getCommentAssignment_2_7_2(), "rule__VacationC__CommentAssignment_2_7_2");
			builder.put(grammarAccess.getVacationCAccess().getCommentAssignment_2_7_3_1(), "rule__VacationC__CommentAssignment_2_7_3_1");
			builder.put(grammarAccess.getVacationCAccess().getFreebusyAssignment_2_8_2(), "rule__VacationC__FreebusyAssignment_2_8_2");
			builder.put(grammarAccess.getVacationCAccess().getFreebusyAssignment_2_8_3_1(), "rule__VacationC__FreebusyAssignment_2_8_3_1");
			builder.put(grammarAccess.getVacationCAccess().getRstatusAssignment_2_9_2(), "rule__VacationC__RstatusAssignment_2_9_2");
			builder.put(grammarAccess.getVacationCAccess().getRstatusAssignment_2_9_3_1(), "rule__VacationC__RstatusAssignment_2_9_3_1");
			builder.put(grammarAccess.getVacationCAccess().getX_propAssignment_2_10_2(), "rule__VacationC__X_propAssignment_2_10_2");
			builder.put(grammarAccess.getVacationCAccess().getX_propAssignment_2_10_3_1(), "rule__VacationC__X_propAssignment_2_10_3_1");
			builder.put(grammarAccess.getVacationCAccess().getIana_propAssignment_2_11_2(), "rule__VacationC__Iana_propAssignment_2_11_2");
			builder.put(grammarAccess.getVacationCAccess().getIana_propAssignment_2_11_3_1(), "rule__VacationC__Iana_propAssignment_2_11_3_1");
			builder.put(grammarAccess.getTimeZoneCAccess().getTzidAssignment_2_0_1(), "rule__TimeZoneC__TzidAssignment_2_0_1");
			builder.put(grammarAccess.getTimeZoneCAccess().getLast_modAssignment_2_1_1(), "rule__TimeZoneC__Last_modAssignment_2_1_1");
			builder.put(grammarAccess.getTimeZoneCAccess().getTzurlAssignment_2_2_1(), "rule__TimeZoneC__TzurlAssignment_2_2_1");
			builder.put(grammarAccess.getTimeZoneCAccess().getX_propAssignment_2_3_2(), "rule__TimeZoneC__X_propAssignment_2_3_2");
			builder.put(grammarAccess.getTimeZoneCAccess().getX_propAssignment_2_3_3_1(), "rule__TimeZoneC__X_propAssignment_2_3_3_1");
			builder.put(grammarAccess.getTimeZoneCAccess().getIana_propAssignment_2_4_2(), "rule__TimeZoneC__Iana_propAssignment_2_4_2");
			builder.put(grammarAccess.getTimeZoneCAccess().getIana_propAssignment_2_4_3_1(), "rule__TimeZoneC__Iana_propAssignment_2_4_3_1");
			builder.put(grammarAccess.getTimeZoneCAccess().getStandardcAssignment_2_5_2(), "rule__TimeZoneC__StandardcAssignment_2_5_2");
			builder.put(grammarAccess.getTimeZoneCAccess().getStandardcAssignment_2_5_3_1(), "rule__TimeZoneC__StandardcAssignment_2_5_3_1");
			builder.put(grammarAccess.getTimeZoneCAccess().getDaylightcAssignment_2_6_2(), "rule__TimeZoneC__DaylightcAssignment_2_6_2");
			builder.put(grammarAccess.getTimeZoneCAccess().getDaylightcAssignment_2_6_3_1(), "rule__TimeZoneC__DaylightcAssignment_2_6_3_1");
			builder.put(grammarAccess.getEventCAccess().getUnorderedGroup_2(), "rule__EventC__UnorderedGroup_2");
			builder.put(grammarAccess.getAlarmCAccess().getUnorderedGroup_2(), "rule__AlarmC__UnorderedGroup_2");
			builder.put(grammarAccess.getTzpropAccess().getUnorderedGroup_2(), "rule__Tzprop__UnorderedGroup_2");
			builder.put(grammarAccess.getTzpropOptionalAccess().getUnorderedGroup_3(), "rule__TzpropOptional__UnorderedGroup_3");
			builder.put(grammarAccess.getComponentAlarmTimeAccess().getUnorderedGroup_3(), "rule__ComponentAlarmTime__UnorderedGroup_3");
			builder.put(grammarAccess.getComponentAlarmEmailPropertyAccess().getUnorderedGroup_2(), "rule__ComponentAlarmEmailProperty__UnorderedGroup_2");
			builder.put(grammarAccess.getToDoCAccess().getUnorderedGroup_2(), "rule__ToDoC__UnorderedGroup_2");
			builder.put(grammarAccess.getJournalCAccess().getUnorderedGroup_2(), "rule__JournalC__UnorderedGroup_2");
			builder.put(grammarAccess.getVacationCAccess().getUnorderedGroup_2(), "rule__VacationC__UnorderedGroup_2");
			builder.put(grammarAccess.getTimeZoneCAccess().getUnorderedGroup_2(), "rule__TimeZoneC__UnorderedGroup_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
